### ISSUE TITLE
[SND] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#173]
Found an audio format that can't be played in BZR2.

BZR's Version: 2.0.21 Alpha

Some samples:

SND

[SND.zip](https://github.com/aargirakis/BZRPlayer/files/9744732/SND.zip)

**Comment by ciros88** [comment]
for what i know exists at least 4 different formats with *.snd extension..
i didn't recognized these ones you provided: i've tried with all players i have, without success
@aargirakis have u tried them?

**Comment by ciros88** [comment]
played with audacity (raw data importing): they are 8khz raw data samples, so it is confirmed that they are not music files

**Comment by ciros88** [comment]
@aargirakis FMOD is able to play them, it isn't?

**Comment by rayman3003** [comment]
Yeap, They are probably raw data samples.

**Comment by aargirakis** [comment]
Well, it doesn't HAVE to be music files. It can be sound files. Although i would help what kind of file it is, the extension doesn't say much.

**Comment by rayman3003** [comment]
All these 10 issues that I made topics for them (from two days ago), are all from a folder, containing more than 18000 music files of old chiptunes that I grabbed some years ago.

Unfortunately I don't remember which website I grabbed them from. But the folder's name is:

**Modules-16K**

**Comment by ciros88** [comment]
it isn't easy to handle with .snd, because, if you see here:
https://www.voxtab.com/downloads/Voxtab_File_Formats_List.pdf
there are 3 different snd formats. plus, already 2 snd format exists, reading here:
https://en.wikipedia.org/wiki/Digital_sound_file_formats_using_the_.snd_extension

for what i've understood, the snd provided in this issue are none of these but raw samples.
the problem with raw samples is you don't know how to play them (e.g. khz), it isn't hardcoded in the file itself for what i know.
so, support for raw snd samples would be "bad" in my opinion. but, support for other types of snd files could be cool for sure
