### ISSUE TITLE
[IMS] Plays, but no sound

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#186]
BZR can play these audio file format, But I can't hear any sound!

So I think it's a bug?

BZR's Version: 2.0.21 Alpha

Note: I'm not 100% sure if they r music files or not.

IMS

[IMS.zip](https://github.com/aargirakis/BZRPlayer/files/9768803/IMS.zip)

**Comment by ciros88** [comment]
@aargirakis on [bzr](http://bzrplayer.blazer.nu/formats.php) there is: "Images Sound System" "ims" "amiga".
but really dunno what it is. for what i know ims is:
https://moddingwiki.shikadi.net/wiki/IMS_Format
also nothing appears with these two google queries:
"images sound system" "ims"
"images sound system" "amiga"
@aargirakis do you have some "ims" sample tracks?

**Comment by aargirakis** [comment]
This is the format supported https://www.exotica.org.uk/wiki/Beast_Busters
Those attached .ims are some other format I do not know of.

**Comment by aargirakis** [comment]
By the way, UADE will try to play everything if it's the right file extension.

**Comment by ciros88** [comment]
so should be "Image Music System" not "Images Sound System" as reported [here](http://bzrplayer.blazer.nu/formats.php)

**Comment by ciros88** [comment]
btw bzr1 it is capable to play this:
https://www.exotica.org.uk/wiki/The_Hunt_for_Red_October_-_Based_on_the_Movie
but not bzr2: it tries with libxmp not UADE, recognize the correct format and track details but  remains stucked)

**Comment by ciros88** [comment]
could be interesting to also have support for https://moddingwiki.shikadi.net/wiki/IMS_Format
that is the format of the original attached files in [IMS.zip](https://github.com/aargirakis/BZRPlayer/files/9768803/IMS.zip)
because it is consistend with the format headers (the presence of "ww" before the instrument names).
also, i've found CADILLAC.IMS attached in https://github.com/aargirakis/BZRPlayer/files/9768803/IMS.zip here;
https://modland.ziphoid.com/incoming/laboratory/adlib/ims/
so, it is confirmed (thanks to ziphoid! xD )
i think we have 2 issues here: support for "Images Music System" and for "AdLib IMS"
