### ISSUE TITLE
[smus] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#241]
Found an audio format that can't be played in BZR2. (It makes the BZR2 to crash too!)

BZR's Version: 2.0.25 Alpha

Note: Probably they r music files, bcuz of the name of the first file "axel f". & smus - smusic

Note2: All of them located in a folder named SoniX

Some samples:

[smus.zip](https://github.com/aargirakis/BZRPlayer/files/9943783/smus.zip)

**Comment by ciros88** [comment]
bzr2 already support smus format (through uade), but as you can read here:
[http://fileformats.archiveteam.org/wiki/SMUS](url)
instrument files are needed for playing them. an example:
https://www.exotica.org.uk/wiki/Stellar_7

(just an hint: maybe try to do a little research before posting a "not playable" issue, in order to make things easier for us)
