### ISSUE TITLE
Support of Repeat playback of sid's subsongs (sid)

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#282]
Whenever we have a sid (c64) tune that has more than 1 subsongs, Enabling repeat in BZR2 (v2.0.33 Alpha), won't repeat any subsongs of the file.

Example (try with it's subsongs):

[A.zip](https://github.com/aargirakis/BZRPlayer/files/10201004/A.zip)

**Comment by ciros88** [comment]
if i've understood what u mean, then yeah this is not an issue but the desidered behaviour.

"repeat sid" function existed until 2.0.12b.Alpha release, but starting from 2.0.13.Alpha this is not possible anymore as #32 has been implemented.

Thanks to #32 bzr2 treats any subtune as an indipendent tracklist entry, and this has various advantages: think about a sid with 1 subtune as the main theme, and 10 other subtunes as "useless" videogame FXs that you are not really interested lo listen.

Before 2.0.13.Alpha a sid with multiple subtunes was treated as a single tracklist entity, and this means you was forced to hear every subtune unless you manually skip them.

Starting from 2.0.13.Alpha instead, you can have a playlist where you add only subtunes you really want to listen.
so having #32 implemented, when you add a sid with multiple subtunes to the tracklist it stops to be treated as a single sid entity but instead, as multiple indipendent tracks, that doesn't share nothing because they are not part of a single sid entity anymore.

now, trying to implement a "repeat sid" would lead to problematic scenarios; thing about this scenario:

add to the tracklist an mp3 and, below, a sid with 10 subtunes, now take the first 5 subtunes and put them above the mp3: you will have 5 subtunes, then the mp3, then the remaining 5 subtunes: how should behave a "repeat sid" function?

since we choosed to treat subtunes as intipendent track list entities we already knew the "repeat sid" functionality would be lost, but benefits gained with #32 far outweigh its disadvantages.

give me feedback if i've got a point so i can close this issue.

**Comment by ciros88** [comment]
I figured you needed to repeat a whole sid with its all subsongs, that means: a sid has 10 subtunes, and you needed a function for loop through these subtunes starting from 1 to 10 then to 1 again., and this is not possible anymore.

but, if you need to repeat a single subtune only then just enable "repeat one" function clicking two times on repeat icon and (thanks to #32 whatever is it an mp3 or a sid subune) the single selected tracklist entry will be looped.

was this what you meant?

**Comment by rayman3003** [comment]
> but, if you need to repeat a single subtune only then just enable "repeat one" function clicking two times on the repeat icon and (thanks to #32 whatever is it an mp3 or a sid subune) the single selected tracklist entry will be looped.
> 
> was this what you meant?

OK. It seems I made a mistake. & also Uploaded a wrong sid file.

Please close this issue. & I will make a new issue & upload a new sid file & explain my problem there. :D

Thank u.
