### ISSUE TITLE
add "Artist" or "Author" column to tracklist

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#359]
maybe 'Artist' is more generic and better applies to all situations (sometimes the artist differ from the author)

**Comment by aargirakis** [comment]
This is a very big issue and should be called something "Custom columns for playlists - which could be, artist, bitrate, fileformat, date created, track number". So either we have what we have or we should have custom columns with custom orders and widths etc. There is no inbetween since "Artist" isn't a field/metadata/filename which could always read from the file.

**Comment by ciros88** [comment]
Yeah, i think artist is something people would like to know and some formats have this information like sids also. For the others will be blank for sure.

**Comment by ciros88** [comment]
missing ones:
flac, sndh, sc68

also utf8 support is missing

**Comment by ciros88** [comment]
test tracks:
[tracks.zip](https://github.com/aargirakis/BZRPlayer/files/13204041/tracks.zip)

**Comment by ciros88** [comment]
ogg id tag with utf16 chars:
[ogg with utf16 chars.zip](https://github.com/aargirakis/BZRPlayer/files/13208467/ogg.with.utf16.chars.zip)
