### ISSUE TITLE
display sid tracks duration

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#59]

**Comment by ciros88** [comment]
need to be reopened:
song length is not working for a lot of sids (see the attachment)
[sids.zip](https://github.com/aargirakis/BZRPlayer/files/9439128/sids.zip)

**Comment by ciros88** [comment]
add a preference for setting a custom Songlengths path

**Comment by aargirakis** [comment]
Do you have an example of a sid not in HVSC that has a length in ZXTune?

**Comment by ciros88** [comment]
if i well understood, zxtune put a default length of 3minutes when doesn't know the duration. but there, im  attaching sids where duration is recognized in zxtune but not in bzr:
[sids.zip](https://github.com/aargirakis/BZRPlayer/files/9533059/sids.zip)
dunno if they are in hsvc, need to check. maybe we could do this when already having a preference entry for setting a custom Songlengths path, so i can do all the checks easily

**Comment by aargirakis** [comment]
Hmm... I modified a sid, changed metadata etc. And ZXTune still finds the correct length, I'll have to check the source to see If I can understand how he gets the song length.

**Comment by ciros88** [comment]
yeah! some days ago in discord i've pasted you where zxtune gets track duration

**Comment by aargirakis** [comment]
OK, I think I've got it now. He uses the old version of calculating the hash, which skips the header of the sid. That's the most likely thing to change in HSVC (one of your files they had changed the comments, thus breaking the checksum match).
So the new way of calculating hash is simpler but also means that songlengths file and HSVC versions preferebly should match.

I think this might be a pretty good solution:
First check with new hash check and newest songlength version. (This would work most of the time)
Otherwise:
Calculate old hash (that doesn't use header) and use songlenth.txt instead of songlength.md5

There is a tool here for converting the format: https://hvsc.de/download/files/tools/ConvertMd5ToSldbTxt.zip

**Comment by ciros88** [comment]
seems a good solution

**Comment by aargirakis** [comment]
OK, done. Works better now, most of the files that has a length in ZXTune now has a length in BZR. Some of those files is missing in the songlengths file and they don't get a length in ZXTune either. There was at least one which got a length in ZXTune and not in BZR, I'm guessing it's because he used an older songlength file.
